"""Default XDG configuration.

``praxis-prime config`` writes these files. Compliance dials are included and
set to off. Writing the files does not start the daemon and does not enable a
dial.

TODO: ARCHITECTURE §17 and §25.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from praxis_prime.paths import config_dir
from praxis_prime.policy.dials import default_positions

_CONFIG_HEADER = """\
# Praxis Prime configuration (pre-alpha skeleton).
# Generated by `praxis-prime config`. Safe to edit. Contains no secrets.
#
# Secrets do not belong in this file. Use the OS keychain or secrets.env.age
# (ARCHITECTURE §25). Cloud model names below are examples. No API keys are
# read or stored.
#
# Compliance dials default to off (ARCHITECTURE §17). A dial position is one
# of: off, monitor, enforce. Dial hooks do nothing while a dial is off.
# The baseline safety spine is not a dial and cannot be turned off.
#
# The Decision Engine is local. It does not call a hosted decision service.
# decide.prescreen defaults to false, so approvals are unchanged until you
# turn it on. The engine cannot auto-approve git push, force operations,
# deletes of tracked files, or writes outside the task worktree.
#
# mcp.serve stays false. Nothing listens for other agents until you run
# `praxis-prime mcp serve`. Browser profile defaults to a disposable
# directory. Playwright is optional; without it the browser tool uses web_fetch.
"""

_PROFILE_HEADER = """\
# Which compliance dials are active. An empty list means every dial is off.
# TODO: ARCHITECTURE §17.1. This file does not enable enforcement.
"""


@dataclass(frozen=True, slots=True)
class ConfigWriteResult:
    """Result of attempting to write the default config."""

    config_path: Path
    profile_path: Path
    wrote: bool


def default_config_document() -> dict[str, object]:
    """Return the default config as nested dicts. Every dial is off."""
    return {
        "core": {
            "profile": "default",
            "mode": "ask",
            "locale": "en-US",
            "timezone": "America/New_York",
        },
        "dials": default_positions(),
        "models": {
            "primary": "ollama:qwen3:32b",
            "utility": "ollama:qwen3:8b",
            "reviewer": "anthropic:claude-sonnet",
            "vision": "ollama:qwen2.5-vl",
            "embed": "local:bge-small",
        },
        "decide": {
            "enabled": True,
            "prescreen": False,
            "profile": "gpu-8g",
            "max_tier": 4,
            "tiers": ["rules", "classifiers", "llm_judge", "jury"],
            "min_confidence": 0.8,
            "disagreement_js": 0.15,
            "aggregation": "confidence-weighted",
            "jury_size": 3,
            "escalate_to_human": False,
            "latency_budget_ms": {"default": 800, "voice": 300},
            "models": {
                "tier2": "ollama:qwen3:8b",
                "tier4": "ollama:qwen3:32b",
            },
            "judges": {
                "backend": "ollama",
                "models": ["ollama:qwen3:8b", "ollama:qwen3:1.7b"],
                "personas": [
                    "skeptic",
                    "safety",
                    "domain",
                    "cost",
                    "user-advocate",
                ],
            },
            "budgets": {"max_usd": 0.05, "max_calls": 8},
            "calibration": {"method": "auto", "recalibrate": "nightly"},
            "lists": {"allow": [], "deny": []},
        },
        "sandbox": {"default_tier": "bwrap", "network": "off"},
        "jarvis": {
            "enabled": False,
            "wake_word": "hey_praxis",
            "stt": "faster-whisper:small.en",
            "tts": "kokoro",
            "heartbeat_minutes": 15,
            "quiet_hours": "22:00-07:00",
            "home_assistant_url": "http://homeassistant.local:8123",
        },
        "gateway": {
            "listen": "127.0.0.1:18790",
            "socket": "$XDG_RUNTIME_DIR/praxis-prime/prime.sock",
            "approval_ttl_seconds": 900,
        },
        "budgets": {"daily_usd": 5.0, "per_task_usd": 1.0},
        "memory": {
            "redact": "secrets",
            "profile_cap": 20,
            "profile_chars": 4000,
            "episodic_half_life_days": 14,
            "episodic_ttl_days": 90,
        },
        "routines": {"min_interval_seconds": 60, "max_iterations": 20},
        "mcp": {
            "enabled": True,
            "serve": False,
            "lazy_threshold": 8,
            "env_allow": ["PATH", "LANG", "LC_ALL", "LC_CTYPE", "TERM"],
        },
        "browser": {
            "enabled": True,
            "profile": "disposable",
            "allow_domains": [],
            "deny_domains": [],
        },
    }


def default_profile_document() -> dict[str, object]:
    return {"profile": {"name": "default", "mode": "ask", "dials": []}}


def render_config_toml() -> str:
    return _CONFIG_HEADER + "\n" + dumps_toml(default_config_document())


def render_profile_toml() -> str:
    return _PROFILE_HEADER + "\n" + dumps_toml(default_profile_document())


def write_default_config(directory: Path, *, force: bool = False) -> ConfigWriteResult:
    """Write ``config.toml`` and ``policy/profile.toml`` under ``directory``.

    Existing files are left alone unless ``force`` is true. ``directory`` is
    the Praxis Prime config directory itself, not ``~/.config``.
    """
    root = Path(directory)
    config_path = root / "config.toml"
    profile_path = root / "policy" / "profile.toml"
    if config_path.exists() and not force:
        return ConfigWriteResult(config_path, profile_path, wrote=False)
    _atomic_write(config_path, render_config_toml())
    _atomic_write(profile_path, render_profile_toml())
    return ConfigWriteResult(config_path, profile_path, wrote=True)


def resolve_config_dir(
    explicit: str | None = None,
    env: Mapping[str, str] | None = None,
) -> Path:
    if explicit:
        return Path(explicit)
    return config_dir(env)


def dumps_toml(data: Mapping[str, object]) -> str:
    """Serialize a small nested mapping to TOML. Enough for the default file."""
    chunks: list[str] = []
    for key, value in data.items():
        if not isinstance(value, dict):
            raise TypeError(f"top-level {key} must be a table")
        _emit_table(chunks, key, value)
    return "".join(chunks)


def _emit_table(chunks: list[str], prefix: str, table: Mapping[str, object]) -> None:
    scalars: list[tuple[str, object]] = []
    nested: list[tuple[str, Mapping[str, object]]] = []
    for key, value in table.items():
        if isinstance(value, dict):
            nested.append((key, value))
        else:
            scalars.append((key, value))
    if scalars or not nested:
        chunks.append(f"[{prefix}]\n")
        for key, value in scalars:
            chunks.append(f"{key} = {format_toml(value)}\n")
        chunks.append("\n")
    for key, value in nested:
        _emit_table(chunks, f"{prefix}.{key}", value)


def format_toml(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        inner = ", ".join(format_toml(item) for item in value)
        return f"[{inner}]"
    raise TypeError(f"unsupported TOML value: {type(value).__name__}")


def describe_write(result: ConfigWriteResult) -> str:
    """Human-readable summary for the CLI."""
    if not result.wrote:
        return (
            f"praxis-prime config: already exists at {result.config_path}\n"
            "Leave it in place, or pass --force to overwrite.\n"
        )
    count = len(default_positions())
    return (
        f"praxis-prime config: wrote {result.config_path}\n"
        f"praxis-prime config: wrote {result.profile_path}\n"
        f"Compliance dials: {count} configured, all off.\n"
    )


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)
